version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - UPLOAD_MAX_SIZE=10485760
    volumes:
      - ./uploads:/app/uploads
      - ./database.sqlite:/app/database.sqlite
    depends_on:
      - redis
  redis:
    image: redis:6
    ports:
      - '6379:6379'
volumes:
  uploads: